create new target and labels for mpi, sequential and merge mps tests
AntaresSimulatorTeam/antares-xpansion pull request #276
Opened 2021-11-08 14:27 UTC by AbdoulbariZakir

2021-11-24 17:17 UTC, sgatto requested changes
add double labels in order to run oth benders tests using one label

2021-11-24 17:17 UTC, sgatto commented on tests/CMakeLists.txt
> +    set_property(TEST sequential_benders_end_to_end PROPERTY LABELS sequential)
```suggestion
    set_property(TEST sequential_benders_end_to_end PROPERTY LABELS "benders;benders-sequential")
```

2021-11-24 17:17 UTC, sgatto commented on tests/CMakeLists.txt
> +    set_property(TEST mpibenders_benders_end_to_end PROPERTY LABELS mpibenders)
```suggestion
    set_property(TEST mpibenders_benders_end_to_end PROPERTY LABELS "benders;benders-mpi")
```
this way will will run all benders tests by using the old label benders

2021-11-25 08:52 UTC, AbdoulbariZakir commented on tests/CMakeLists.txt
> +    set_property(TEST sequential_benders_end_to_end PROPERTY LABELS sequential)
done!

2021-11-25 10:54 UTC, sgatto approved these changes

2021-11-25 10:56 UTC, merged