Static in-out stabilization of the Benders algorithm
AntaresSimulatorTeam/antares-xpansion pull request #507
Opened 2022-08-25 15:58 UTC by tbittar

Implement the in-out stabilization technique to speed up the convergence of the Benders algorithm

2022-09-14 14:02 UTC, a-zakir commented on src/cpp/benders/logger/CandidateLog.cpp
> +  for (const auto &pairVarnameValue : data.x_cut) {
```
 for (const auto &[name, value] : data.x_cut) {
   
    value_map valuesMap;
    valuesMap[CANDIDATE] = name;
```

2022-09-14 14:49 UTC, a-zakir requested changes

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/CandidateLog.cpp
> +  for (const auto &pairVarnameValue : data.x_cut) {
```suggestion
  for (const auto &[name, value] : data.x_cut) {

    value_map valuesMap;
    valuesMap[CANDIDATE] = name;
    valuesMap[INVEST] =
        get_formatted_string_from_value(value);
    valuesMap[INVEST_MIN] =
        get_formatted_string_from_value(data.min_invest.at(name));
    valuesMap[INVEST_MAX] =
get_formatted_string_from_value(data.max_invest.at(name));
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_sequential/BendersSequential.cpp
> +    _data.stop = should_benders_stop();
```suggestion
    _data.stop = ShouldBendersStop();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
> +    _data.stop = should_benders_stop();
```suggestion
    _data.stop = ShouldBendersStop();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  bool should_benders_stop();
```suggestion
  bool ShouldBendersStop();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +bool BendersBase::should_relaxation_stop() const {
```suggestion
bool BendersBase::ShouldRelaxationStop() const {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +void BendersBase::update_stopping_criterion() {
```suggestion
void BendersBase::updateStoppingCriterion() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +         should_relaxation_stop();
```suggestion
         ShouldRelaxationStop();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +void BendersBase::compute_x_cut() {
```suggestion
void BendersBase::ComputeXCut() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +void BendersBase::compute_invest_cost() {
```suggestion
void BendersBase::ComputeInvestCost() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/BendersBase.cpp
> +    _data.stop = should_benders_stop();
```suggestion
    _data.stop = ShouldBendersStop();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/LastIterationReader.cpp
> +      {},
no need to store `x_in` or `x_out`?

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/WorkerMaster.cpp
> +  define_rhs_with_master_variable(s, x_cut, rhs, rowrhs);
```suggestion
  DefineRhsWithMasterVariable(s, x_cut, rhs, rowrhs);
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/WorkerMaster.cpp
>  void WorkerMaster::define_rhs_with_master_variable(
```suggestion
void WorkerMaster::DefineRhsWithMasterVariable(
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/WorkerMaster.cpp
> +  define_rhs_with_master_variable(s, x_cut, rhs, rowrhs);
```suggestion
  DefineRhsWithMasterVariable(s, x_cut, rhs, rowrhs);
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  void compute_x_cut();
```suggestion
  void ComputeXCut();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  virtual void update_trace();
```suggestion
  virtual void UpdateTrace();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  void compute_invest_cost();
```suggestion
  void ComputeInvestCost();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  virtual void deactivate_integrity_constraints() const;
```suggestion
  virtual void DeactivateIntegrityConstraints() const;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  virtual void activate_integrity_constraints() const;
```suggestion
  virtual void ActivateIntegrityConstraints() const;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  virtual void set_data_pre_relaxation();
```suggestion
  virtual void SetDataPreRelaxation();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  virtual void reset_data_post_relaxation();
```suggestion
  virtual void ResetDataPostRelaxation();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  void update_stopping_criterion();
```suggestion
  void UpdateStoppingCriterion();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/BendersBase.h
> +  bool should_relaxation_stop() const;
```suggestion
  bool ShouldRelaxationStop() const;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/core/ILogger.h
> +  virtual void log_at_initial_relaxation() = 0;
```suggestion
  virtual void LogAtInitialRelaxation() = 0;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_core/include/core/ILogger.h
>    virtual void log_at_switch_to_integer() = 0;
```suggestion
  virtual void LogAtSwitchToInteger() = 0;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
> +      _logger->log_at_switch_to_integer();
```suggestion
      _logger->logAtSwitchToInteger();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
> +  compute_x_cut();
```suggestion
  ComputeXCut();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
> +      _logger->log_at_initial_relaxation();
```suggestion
      _logger->LogAtInitialRelaxation();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_sequential/BendersSequential.cpp
> +    _logger->log_at_initial_relaxation();
```suggestion
    _logger->LogAtInitialRelaxation();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/benders_sequential/BendersSequential.cpp
> +    compute_x_cut();
```suggestion
    ComputeXCut();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/Master.cpp
> +    logger->log_at_initial_relaxation();
```suggestion
    logger->LogAtInitialRelaxation();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/Master.cpp
>      logger->log_at_switch_to_integer();
```suggestion
    logger->LogAtSwitchToInteger();
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/User.cpp
> +void User::log_at_initial_relaxation() {
```suggestion
void User::LogAtInitialRelaxation() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/User.cpp
>  void User::log_at_switch_to_integer() {
```suggestion
void User::LogAtSwitchToInteger() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/UserFile.cpp
> +void UserFile::log_at_initial_relaxation() {
```suggestion
void UserFile::LogAtInitialRelaxation() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/UserFile.cpp
>  void UserFile::log_at_switch_to_integer() {
```suggestion
void UserFile::LogAtSwitchToInteger() {
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/Master.h
>    void log_at_switch_to_integer() override;
```suggestion
  void LogAtSwitchToInteger() override;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/Master.h
> +  void log_at_initial_relaxation() override;
```suggestion
  void LogAtInitialRelaxation() override;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/User.h
>    void log_at_switch_to_integer() override;
```suggestion
  void LogAtSwitchToInteger() override;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/User.h
> +  void log_at_initial_relaxation() override;
```suggestion
  void LogAtInitialRelaxation() override;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/UserFile.h
> +  void log_at_initial_relaxation() override;
```suggestion
  void LogAtInitialRelaxation() override;
```

2022-09-14 14:49 UTC, a-zakir commented on src/cpp/benders/logger/include/logger/UserFile.h
>    void log_at_switch_to_integer() override;
```suggestion
  void LogAtSwitchToInteger() override;
```

2022-09-14 14:49 UTC, a-zakir commented on tests/cpp/TestDoubles/LoggerStub.h
> +  void log_at_initial_relaxation() override {}
```suggestion
  void LogAtInitialRelaxation() override {}
```

2022-09-14 14:49 UTC, a-zakir commented on tests/cpp/TestDoubles/LoggerStub.h
>    void log_at_switch_to_integer() override {}
```suggestion
  void LogAtSwitchToInteger() override {}
```

2022-09-15 08:58 UTC, tbittar commented on src/cpp/benders/benders_core/LastIterationReader.cpp
> +      {},
Indeed no need to store `x_in` or `x_out` as only `x_cut` is useful for the user, and writing `x_in` and `x_out` in the last iteration file would be heavy (this is the list of candidates with an invested value) and confusing

2022-09-20 07:42 UTC, JasonMarechal25 approved these changes

2022-09-20 11:51 UTC, a-zakir approved these changes

2022-09-20 11:51 UTC, merged