update changelog
AntaresSimulatorTeam/antares-xpansion pull request #883
Opened 2024-07-26 08:22 UTC by a-zakir

- New output file **criterions.txt** is added under **lp/** dir to store adequacy criterions for all valid patterns (area+criterion)
- New output file **PositiveUnsuppliedEnergy.txt** is added under **lp/** dir to store the amount of unsupplied energy for all valid patterns (area+criterion)

2024-07-26 08:28 UTC, tbittar requested changes, later dismissed

2024-07-26 08:28 UTC, tbittar commented on docs/user-guide/get-started/adequacy-criterion.md
> +- New output file `criterions.txt` is added under `lp/` dir to store adequacy criterions for all valid patterns (area+criterion)
In this file remove `New output file`, just say `The file xxx, under lp/ dir stores xxx`, same for the next one as this doc will stay the same in future versions

2024-08-06 08:54 UTC, flomnes commented on docs/user-guide/get-started/adequacy-criterion.md
> +- The file `PositiveUnsuppliedEnergy.txt` under `lp/` dir stores the amount of unsupplied energy for all valid patterns (area+criterion)
Can we rename this file to just `unsuppliedEnergy.txt` ?
We have the following convention
- Unsupplied energy
- Spilled energy

2024-08-07 07:30 UTC, a-zakir commented on docs/user-guide/get-started/adequacy-criterion.md
> +- The file `PositiveUnsuppliedEnergy.txt` under `lp/` dir stores the amount of unsupplied energy for all valid patterns (area+criterion)
no, that's the variable name

2024-08-07 07:52 UTC, flomnes approved these changes

2024-08-07 08:29 UTC, merged