add antares-study-updater in installer
AntaresSimulatorTeam/antares-xpansion pull request #96
Opened 2021-03-29 15:21 UTC by jmkerloch

closes #37

2021-03-29 15:26 UTC, flomnes requested changes

2021-03-29 15:26 UTC, flomnes commented on CMakeLists.txt
> +  DESTINATION BIN)
indentation

2021-04-12 08:53 UTC, sgatto approved these changes

2021-04-12 08:57 UTC, flomnes approved these changes

2021-04-12 09:12 UTC, flomnes approved these changes

2021-04-12 11:33 UTC, merged