[Ant-2380] improving maintainability
AntaresSimulatorTeam/antares-xpansion pull request #965
Opened 2024-11-12 16:18 UTC by a-zakir

2024-11-22 17:38 UTC, tbittar requested changes

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/CriterionComputation.h
> -  const OuterLoopInputData outer_loop_input_data_;
Could this attribute also be renamed `criterion_input_data` for consistance ?

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/CriterionComputation.h
- Rename `ComputeOuterLoopCriterion` as `ComputeCriterion`
- Remove all outer loop references in this function variables
- Remove references to outer loops in the comments and descriptions of functions

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/VariablesGroup.h
> +                              outer_loop_single_input_data);
```suggestion
                              criterion_single_input_data);
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/VariablesGroup.h
> +  const std::vector<CriterionSingleInputData>& outer_loop_single_input_data_;
```suggestion
  const std::vector<CriterionSingleInputData>& criterion_single_input_data_;
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/CriterionComputation.cpp
> +    const CriterionInputData &outer_loop_input_data)
```suggestion
    const CriterionInputData &criterion_input_data)
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/CriterionInputDataReader.cpp
> +      throw CriterionCouldNotReadAreaField(err_msg.str(), LOGLOCATION);
```suggestion
      throw CouldNotReadAreaField(err_msg.str(), LOGLOCATION);
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/CriterionInputDataReader.cpp
> +      throw CriterionCouldNotReadCriterionField(err_msg.str(), LOGLOCATION);
```suggestion
      throw CouldNotReadCriterionField(err_msg.str(), LOGLOCATION);
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_core/VariablesGroup.cpp
> +    const std::vector<CriterionSingleInputData>& outer_loop_single_input_data)
```suggestion
    const std::vector<CriterionSingleInputData>& criterion_single_input_data)
```

2024-11-22 17:38 UTC, tbittar commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
Rename `SubproblemData.outer_loop_criterions` and `SubproblemData.outer_loop_pattern_values` as `SubproblemData.criterions` and `SubproblemData.pattern_values` (L181-182)?

2024-11-25 13:21 UTC, a-zakir commented on src/cpp/benders/benders_core/include/antares-xpansion/benders/benders_core/CriterionComputation.h
done

2024-11-25 13:30 UTC, a-zakir commented on src/cpp/benders/benders_mpi/BendersMPI.cpp
yes good idea!

2024-11-25 16:16 UTC, tbittar approved these changes

2024-11-26 15:32 UTC, merged